language: node_js
node_js:
  - '0.10'
  - '0.12'
  - 'iojs'
before_install:
  - apt-get install graphicsmagick imagemagick
after_script:
  - npm install coveralls && cat ./coverage/lcov.info | coveralls
